- name: launch new instance
  amazon.aws.ec2_instance:
    name: amazonlinux2
    region: ap-southeast-3
    key_name: ec2-user
    instance_type: t3.micro
    security_group: ssh-web
    vpc_subnet_id: subnet-0276d466994fa3087
    network:
      assign_public_ip: true
      delete_on_termination: true
    image_id: ami-0de34ee5744189c60 
    volumes: 
      - device_name: /dev/xvda
        ebs: 
          volume_size: 8
          volume_type: gp2
          delete_on_termination: true
  tags:
    - ec2_new
