---

localhost:
  hosts:
    127.0.0.1:
      temp_pass: passwordup2U!
      user1: name1
      user2: name2
      user3: name3
      user4: name4
      user5: name5
      user6: name6
      group1: developer
      group2: programmer
      group3: engineer

ec2:
  hosts:
    10.0.0.1:
    172.16.0.1:
    192.168.0.1:

new:
  hosts:
    172.31.0.1:
  vars:
    hostname: amazonlinux2
